import ArtGallery from "@/components/HomePage/Gallery";
import HeroSection from "../components/HomePage/HeroSection";
import Slidering from "@/components/HomePage/Slidering";

export const metadata = {
  title: 'Reshan - HomePage',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div >
      <HeroSection />
      <ArtGallery />
    </div>
  );
}
