import Featured from "@/components/HomePage/Featured";
import HeroSection from "../components/HomePage/HeroSection";
import OnProgress from "@/components/HomePage/OnProgress";

export const metadata = {
  title: 'Reshan - HomePage',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <div >
      <HeroSection />
      <Featured />
      <OnProgress />

    </div>
  );
}
