import React from 'react';
import ProjectsSection from '../../components/Sculptures/ProjectsSection';

export const metadata = {
  title: "Reshan - Projects",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div className='mt-8'>
      <ProjectsSection />
    </div>
  );
};

export default Page;
